HTML = r'''<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>TruPixel v3</title>
<style>
:root{--bg:#090c12;--panel:#111722;--panel2:#171e2c;--text:#edf1f7;--muted:#97a2b3;--border:#2a3448;--a:#8590ff;--b:#5be0c8;--danger:#ff7171}
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,Arial;background:radial-gradient(circle at top,#151d2c 0,#090c12 60%);color:var(--text)}
.wrap{max-width:1400px;margin:auto;padding:26px 18px 50px}.hero{display:flex;justify-content:space-between;gap:16px;align-items:end;margin-bottom:18px}h1{margin:0;font-size:42px}.sub{color:var(--muted);margin-top:7px}.pill{border:1px solid #28554d;color:var(--b);border-radius:999px;padding:7px 10px;font-size:12px}
.layout{display:grid;grid-template-columns:400px 1fr;gap:18px}.card{background:rgba(17,23,34,.95);border:1px solid var(--border);border-radius:18px;padding:17px;box-shadow:0 12px 34px rgba(0,0,0,.2)}h2{font-size:18px;margin:0 0 13px}label{display:block;color:var(--muted);font-size:13px;margin:13px 0 7px}
.tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.tab,.btn{border:1px solid var(--border);background:var(--panel2);color:var(--text);border-radius:11px;padding:10px;cursor:pointer;font-weight:650}.tab.active,.primary{background:linear-gradient(90deg,var(--a),#ad91ff);border-color:transparent}.primary{width:100%;padding:14px;margin-top:16px}.btn:disabled{opacity:.45;cursor:not-allowed}
.drop{border:1px dashed #506083;border-radius:15px;padding:18px;text-align:center;background:rgba(133,144,255,.05);cursor:pointer}.drop.over{border-color:var(--b);background:rgba(91,224,200,.07)}.fileinfo{font-size:12px;color:var(--muted);margin-top:8px}.hidden{display:none!important}
.row{display:grid;grid-template-columns:1fr 1fr;gap:9px}.row3{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}input[type=number]{width:100%;background:var(--panel2);border:1px solid var(--border);border-radius:10px;color:var(--text);padding:11px}.check{display:flex;align-items:center;gap:8px;background:var(--panel2);border:1px solid var(--border);border-radius:10px;padding:9px 11px;margin-top:8px;font-size:13px;color:var(--text)}
.status{font-size:13px;color:var(--muted);min-height:20px;margin-top:10px}.status.ok{color:var(--b)}.status.err{color:var(--danger)}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.chip{font-size:11px;color:var(--muted);border:1px solid var(--border);border-radius:999px;padding:6px 9px}
.compare{position:relative;height:440px;border:1px solid var(--border);border-radius:15px;overflow:hidden}.checker{background-color:#151922;background-image:linear-gradient(45deg,#222836 25%,transparent 25%),linear-gradient(-45deg,#222836 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#222836 75%),linear-gradient(-45deg,transparent 75%,#222836 75%);background-size:24px 24px;background-position:0 0,0 12px,12px -12px,-12px 0}.darkbg{background:#080b10}.compare img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;image-rendering:pixelated}.afterwrap{position:absolute;inset:0 auto 0 0;width:50%;overflow:hidden;border-right:2px solid rgba(255,255,255,.8)}input[type=range]{width:100%;margin-top:9px}
.three{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:12px}.box{min-height:230px;border:1px solid var(--border);border-radius:13px;display:flex;align-items:center;justify-content:center;overflow:hidden}.box img{max-width:100%;max-height:310px;image-rendering:pixelated}.label{font-size:12px;color:var(--muted);margin-bottom:7px}
pre{margin:0;white-space:pre-wrap;word-break:break-word;max-height:340px;overflow:auto;font-size:12px;line-height:1.5}.batchgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:10px}.batchitem{border:1px solid var(--border);border-radius:12px;padding:9px;background:#0b1018}.batchitem img{width:100%;height:150px;object-fit:contain;image-rendering:pixelated}.history{display:grid;gap:8px}.hist{display:grid;grid-template-columns:52px 1fr;gap:9px;align-items:center;background:var(--panel2);border:1px solid var(--border);border-radius:10px;padding:8px}.hist img{width:52px;height:52px;object-fit:contain;image-rendering:pixelated}.tiny{font-size:11px;color:var(--muted)}
.feedback{display:flex;gap:8px;margin-top:11px}.feedback .btn{flex:1}.note{font-size:11px;color:var(--muted);margin-top:12px}@media(max-width:1050px){.layout{grid-template-columns:1fr}.three{grid-template-columns:1fr}.compare{height:330px}}
</style>
</head>
<body><div class="wrap">
<div class="hero"><div><h1>TruPixel v3</h1><div class="sub">Reconstrução pixel-perfect, spritesheets, batch, auto-crop e aprendizado comunitário.</div></div><div class="pill">community learning online</div></div>
<div class="layout">
<div class="card">
<h2>Entrada</h2>
<label>Modo</label><div class="tabs"><button class="tab active" data-mode="single">Imagem</button><button class="tab" data-mode="sheet">Spritesheet</button><button class="tab" data-mode="batch">Batch</button></div>
<label>Arquivos</label><div id="drop" class="drop"><b>Arraste e solte aqui</b><div class="fileinfo">ou clique para selecionar</div><div id="fileinfo" class="fileinfo">Nenhum arquivo</div><input id="files" class="hidden" type="file" accept="image/*" /></div>
<div id="singleFields"><div class="row"><div><label>Largura alvo</label><input id="tw" type="number" placeholder="64" min="1" max="4096"></div><div><label>Altura alvo</label><input id="th" type="number" placeholder="64" min="1" max="4096"></div></div></div>
<div id="sheetFields" class="hidden"><div class="row"><div><label>Frame width</label><input id="fw" type="number" placeholder="64"></div><div><label>Frame height</label><input id="fh" type="number" placeholder="64"></div></div><div class="row"><div><label>Saída/frame W</label><input id="stw" type="number" placeholder="64"></div><div><label>Saída/frame H</label><input id="sth" type="number" placeholder="64"></div></div></div>
<label>Paleta máxima</label><input id="palette" type="number" value="32" min="2" max="256">
<label class="check"><input id="cleanup" type="checkbox" checked> Limpar pixels isolados</label>
<label class="check"><input id="autocrop" type="checkbox" checked> Auto-crop de margens transparentes</label>
<button id="run" class="tab primary">Reconstruir</button><div id="status" class="status">Pronto.</div><div class="note">Uso online registra apenas métricas de eficácia no Neon. A arte bruta não entra no corpus por padrão.</div>
</div>
<div style="display:grid;gap:16px">
<div class="card"><h2>Resultado</h2><div class="toolbar"><button id="download" class="btn" disabled>Baixar PNG</button><button id="downloadZip" class="btn" disabled>Baixar ZIP</button><button id="copyDiag" class="btn" disabled>Copiar diagnóstico</button><button id="bgToggle" class="btn">Fundo: quadriculado</button><span id="modechip" class="chip">sem resultado</span></div>
<div id="compare" class="compare checker"><img id="before"><div id="afterwrap" class="afterwrap"><img id="after"></div></div><input id="slider" type="range" min="0" max="100" value="50">
<div class="three"><div><div class="label">Original</div><div class="box checker"><img id="orig"></div></div><div><div class="label">Reconstruído</div><div class="box checker"><img id="result"></div></div><div><div class="label">Diff</div><div class="box darkbg"><img id="diff"></div></div></div>
<div class="feedback"><button id="good" class="btn" disabled>👍 Ficou bom</button><button id="bad" class="btn" disabled>👎 Precisa melhorar</button></div>
</div>
<div id="batchCard" class="card hidden"><h2>Batch</h2><div id="batchgrid" class="batchgrid"></div></div>
<div class="card"><h2>Diagnóstico</h2><pre id="diag">Nenhum processamento ainda.</pre></div>
<div class="card"><h2>Histórico local</h2><div id="history" class="history"><div class="tiny">Ainda vazio.</div></div></div>
</div></div></div>
<script>
const S={mode:'single',files:[],original:null,result:null,diff:null,zip:null,jobIds:[],diag:null,bg:'checker',historyKey:'trupixel_v3_history'};
const $=id=>document.getElementById(id); const E={drop:$('drop'),files:$('files'),fileinfo:$('fileinfo'),single:$('singleFields'),sheet:$('sheetFields'),run:$('run'),status:$('status'),before:$('before'),after:$('after'),afterwrap:$('afterwrap'),orig:$('orig'),result:$('result'),diff:$('diff'),slider:$('slider'),download:$('download'),downloadZip:$('downloadZip'),copyDiag:$('copyDiag'),bgToggle:$('bgToggle'),compare:$('compare'),modechip:$('modechip'),diag:$('diag'),batchCard:$('batchCard'),batchgrid:$('batchgrid'),good:$('good'),bad:$('bad'),history:$('history')};
function status(t,k=''){E.status.textContent=t;E.status.className='status '+k}function mode(m){S.mode=m;document.querySelectorAll('.tab[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));E.single.classList.toggle('hidden',m!=='single');E.sheet.classList.toggle('hidden',m!=='sheet');E.files.multiple=m==='batch';if(m!=='batch'&&S.files.length>1)S.files=S.files.slice(0,1);updateFileInfo()}
document.querySelectorAll('.tab[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));
function updateFileInfo(){E.fileinfo.textContent=S.files.length?S.files.map(f=>f.name).join(', '):'Nenhum arquivo'}function setFiles(list){S.files=[...list];if(S.mode!=='batch')S.files=S.files.slice(0,1);updateFileInfo();if(S.files[0]){const r=new FileReader();r.onload=()=>{S.original=r.result;E.before.src=r.result;E.orig.src=r.result};r.readAsDataURL(S.files[0])}}
E.drop.onclick=()=>E.files.click();E.files.onchange=()=>setFiles(E.files.files);['dragenter','dragover'].forEach(n=>E.drop.addEventListener(n,e=>{e.preventDefault();E.drop.classList.add('over')}));['dragleave','drop'].forEach(n=>E.drop.addEventListener(n,e=>{e.preventDefault();E.drop.classList.remove('over')}));E.drop.addEventListener('drop',e=>setFiles(e.dataTransfer.files));
E.slider.oninput=()=>E.afterwrap.style.width=E.slider.value+'%';function dataUrl(b64){return'data:image/png;base64,'+b64}function dlData(url,name){const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove()}function dlB64(b64,name,mime='application/zip'){const a=document.createElement('a');a.href='data:'+mime+';base64,'+b64;a.download=name;document.body.appendChild(a);a.click();a.remove()}
E.download.onclick=()=>S.result&&dlData(S.result,'trupixel_result.png');E.downloadZip.onclick=()=>S.zip&&dlB64(S.zip,'trupixel_export.zip');E.copyDiag.onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(S.diag,null,2));status('Diagnóstico copiado.','ok')};
E.bgToggle.onclick=()=>{S.bg=S.bg==='checker'?'dark':'checker';document.querySelectorAll('.box').forEach(x=>{if(!x.contains(E.diff)){x.classList.toggle('checker',S.bg==='checker');x.classList.toggle('darkbg',S.bg==='dark')}});E.compare.classList.toggle('checker',S.bg==='checker');E.compare.classList.toggle('darkbg',S.bg==='dark');E.bgToggle.textContent='Fundo: '+(S.bg==='checker'?'quadriculado':'escuro')};
function saveHist(){if(!S.result)return;const h=JSON.parse(localStorage.getItem(S.historyKey)||'[]');h.unshift({result:S.result,mode:S.mode,when:new Date().toLocaleString('pt-BR'),target:S.diag?.target_size||null});try{localStorage.setItem(S.historyKey,JSON.stringify(h.slice(0,4)))}catch{}renderHist()}function renderHist(){let h=[];try{h=JSON.parse(localStorage.getItem(S.historyKey)||'[]')}catch{};E.history.innerHTML=h.length?h.map(x=>`<div class="hist"><img src="${x.result}"><div><b>${x.mode}</b><div class="tiny">${x.when}${x.target?' • '+x.target.join('×'):''}</div></div></div>`).join(''):'<div class="tiny">Ainda vazio.</div>'}
async function feedback(outcome){if(!S.jobIds.length)return;const fd=new FormData();fd.append('action','feedback');fd.append('job_ids',S.jobIds.join(','));fd.append('outcome',outcome);const r=await fetch(window.location.pathname,{method:'POST',body:fd});if(r.ok){status(outcome==='accepted'?'Feedback positivo registrado.':'Feedback negativo registrado.','ok');E.good.disabled=E.bad.disabled=true}else status('Não consegui registrar o feedback.','err')}
E.good.onclick=()=>feedback('accepted');E.bad.onclick=()=>feedback('rejected');
function applyMain(data){S.result=dataUrl(data.result_png_base64);S.diff=dataUrl(data.diff_png_base64);S.jobIds=data.job_ids||[];S.diag=data.diagnostics;E.result.src=S.result;E.diff.src=S.diff;E.after.src=S.result;E.diag.textContent=JSON.stringify(S.diag,null,2);E.download.disabled=false;E.copyDiag.disabled=false;E.good.disabled=E.bad.disabled=false;E.modechip.textContent=data.mode;saveHist()}
async function run(){if(!S.files.length){status('Selecione arquivo(s).','err');return}try{status('Processando...');E.run.disabled=true;E.batchCard.classList.add('hidden');E.downloadZip.disabled=true;S.zip=null;const fd=new FormData();fd.append('action','reconstruct');fd.append('mode',S.mode);fd.append('max_palette',$('palette').value||'32');fd.append('cleanup_isolated',$('cleanup').checked?'true':'false');fd.append('auto_crop',$('autocrop').checked?'true':'false');S.files.forEach(f=>fd.append('images',f));if(S.mode==='single'){if($('tw').value)fd.append('target_width',$('tw').value);if($('th').value)fd.append('target_height',$('th').value)}if(S.mode==='sheet'){if(!$('fw').value||!$('fh').value)throw new Error('Informe frame width e frame height.');fd.append('frame_width',$('fw').value);fd.append('frame_height',$('fh').value);if($('stw').value)fd.append('target_width',$('stw').value);if($('sth').value)fd.append('target_height',$('sth').value)}const r=await fetch(window.location.pathname,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Erro ao processar.');if(d.mode==='batch'){E.batchCard.classList.remove('hidden');E.batchgrid.innerHTML=d.results.map((x,i)=>`<div class="batchitem"><img src="${dataUrl(x.result_png_base64)}"><div class="tiny">${x.filename||'imagem '+(i+1)}</div><button class="btn" style="width:100%;margin-top:7px" onclick="dlData('${dataUrl(x.result_png_base64)}','trupixel_${i+1}.png')">Baixar</button></div>`).join('');const first=d.results[0];applyMain({mode:'batch',result_png_base64:first.result_png_base64,diff_png_base64:first.diff_png_base64,job_ids:d.job_ids,diagnostics:{mode:'batch',count:d.results.length,learning_backend:d.learning_backend,community_contribution_recorded:true,items:d.results.map(x=>({filename:x.filename,diagnostics:x.diagnostics}))}});S.zip=d.batch_zip_base64;E.downloadZip.disabled=false}else{applyMain(d);if(d.frames_zip_base64){S.zip=d.frames_zip_base64;E.downloadZip.disabled=false}}status('Concluído.','ok')}catch(e){status(e.message||'Erro inesperado.','err')}finally{E.run.disabled=false}}
E.run.onclick=run;mode('single');renderHist();
</script></body></html>'''
